Befunde sollten verständlich sein. Verständlichkeit erreicht man über vier Mittel: Einfachheit, Prägnanz, Struktur und Leseanreize. In diesem Sinne möchte ich gerne radiologische Befunde optimieren.

* CC-Lizenz zur freien Verwendung

Die Texte sind zur freien Verwendung mit der [[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International License]] Lizenz versehen.

* Ganzkörper CT :: 8cgk
Rechtfertigene Indikation: Osteolysen?

Technik: Spiral-CT des gesamten Körpers soweit technisch erfassbar in Niedrigdosistechnik.

Befund:
Keine sichere Beurteilbarkeit der Weichteile bei Niedrigdosistechnik.
Schädel: Unauffällig.
HWS: Unauffällig.
Obere Extremität soweit erfasst: Unauffällig.
Rippen: Unauffällig.
BWS: Unauffällig.
Lunge: Unauffällig.
LWS: Unauffällig.
Becken: Unauffällig.
Untere Extremität soweit erfasst: Unauffällig.

Beurteilung:
Kein Nachweis von Osteolysen

* CCT :: 8cctnorm
Rechtfertigende Indikation: Blutung? Ischämie? Hirndruck?

Technik: CCT nativ nach SOP.

Befund
Blutungssuspekte Dichteanhebungen: Nein.
Innere Liquorräume: Unauffällig.
Äußere Liquorräume: Unauffällig. 
Mittellinie: Nicht verlagert.
Mediazeichen: Nein.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Venöse Sinus: Soweit beurteilbar unauffällig.
Nasennebenhöhlen: Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
- Kein Anhalt für eine intrakranielle Einblutung.
- Ein frischer territorialer Infarkt demarkiert sich nicht.
- Keine Zeichen eines erhöhten Hirndruckes.

* CCT alter Mensch :: 8cctalt
Rechtfertigende Indikation: Blutung? Ischämie? Hirndruck?

Technik: CCT nativ nach SOP.

Befund
Blutungssuspekte Dichteanhebungen: Nein.
Innere Liquorräume: Mäßig erweitert. Keine typische NPH-Konfiguration. Keine eindeutige temporomesial betonte Atrophie. Unauffällige Breite der Temporalhörner.
Äußere Liquorräume: Mäßig erweitert. 
Mittellinie: Nicht verlagert.
Mediazeichen: Nein.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Venöse Sinus: Soweit beurteilbar unauffällig.
Nasennebenhöhlen: Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
- Kein Anhalt für eine intrakranielle Einblutung.
- Ein frischer territorialer Infarkt demarkiert sich nicht.
- Keine Zeichen eines erhöhten Hirndruckes.

* CCT alt + Mikroangiopathie und/oder Lakunen :: 8cctm
Rechtfertigende Indikation: Blutung? Ischämie? Hirndruck?

Technik: CCT nativ nach SOP.

Befund
Blutungssuspekte Dichteanhebungen: Nein.
Innere Liquorräume: Mäßig erweitert. Keine typische NPH-Konfiguration. Keine eindeutige temporomesial betonte Atrophie. Unauffällige Breite der Temporalhörner.
Äußere Liquorräume: Mäßig erweitert.
Mittellinie: Nicht verlagert.
Mediazeichen: Nein.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar. Dichteminderungen des periventrikulären Marklagers.
Venöse Sinus: Soweit beurteilbar unauffällig.
Nasennebenhöhlen: Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
- Kein Anhalt für eine intrakranielle Einblutung.
- Ein frischer territorialer Infarkt demarkiert sich nicht.
- Dichteminderungen des periventrikulären Marklager, die unter anderem mit mikroangiopathischen und lakunären Veränderungen vereinbar sind. Das Alter lakunärer Veränderungen lässt sich mittels CT nicht zuverlässig einschätzen.
- Keine Zeichen eines erhöhten Hirndruckes.

* MRT Gehirn :: 8cmr
Klinische Angaben

Befund
Diffusionsstörung: Nein.
Pathologische Signalanhebungen in der T1w: Nein.
Innere Liquorräume: Unauffällig. Keine NPH-Konfiguration.
Äußere Liquorräume: Unauffällig. Keine signifikante temporomesiale Atrophie.
Mittellinie: Nicht verlagert.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Hirnstamm: Unauffällig.
Kleinhirn: Unauffällig. Auch unauffällige Lage der Kleinhirntonsillen.
Marklager: In der T2w und in der FLAIR zeigen sich einzelne unspezifische Signalanhebungen im periventrikulären Marklager.
Nasennebenhöhlen: Soweit erfasst unauffällige Signale.
Mastoidzellen: Soweit erfasst unauffällige Signale. Frei einsehbarer innerer Gehörgang.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Einzelne unspezifische Marklagerveränderungen. Diese sind gut mit mikroangiopathisch und lakunär bedingten Veränderungen vereinbar. Ansonsten kein richtungsweisender Befund.

* CT-NNH :: 8cnnh
Rechtfertigende Indikation
Belüftung der Nasennebenhöhlen?

Technik
Spiral-CT der Nasennebenhöhlen

Beurteilung
Sinus frontales: Unauffällige Belüftung.
Sinus ethmoidales: Unauffällige Belüftung.
Sinus sphenoidales: Unauffällige Belüftung.
Sinus maxillares: Unauffällige Belüftung.
Mastoidzellen: Unauffällige Belüftung.
Spiegelbildungen: Nein.
Nasenseptum: Leichte Deviation.
Conchae nasalis: Unauffällig.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

* CT-Felsenbein :: 8cfb
Rechtfertigende Indikation
Pathologie der Felsenbeine?

Technik
Spiral-CT der Felsenbeine

Befund
Mastoidzellen: unauffällig
Äußerer Gehörgang: unauffällig
Gehörknöchelchen: unauffällig
Prussak-Raum: unauffällig
Scutum: unauffällig
Lateraler Bogengang: unauffällig.
Tegmen tympani: unauffällig
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung:
Kein richtungsweisender Befund

* CT-HWS :: 8chws
Rechtfertigende Indikation
Spinale Enge? Degeneration? Fraktur?

Technik
Spiral-CT der HWS.

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderungen von Wirbelkörpern: Nein.
Miterfasste basale Hirnabschnitte: Unauffällig soweit erfasst.
HWK1/2: Keine Fraktur.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR-HWS :: 8mhws
Fragestellung
Spinale Enge? Degeneration?

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderungen von Wirbelkörpern: Nein.
Miterfasste basale Hirnabschnitte: Unauffällig soweit erfasst.
Myelon: Unauffällig.
HWK1/2: Keine Fraktur.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MRT Schulter :: 8mschul
Klinische Angaben
Verletzung der Rotatorenmanschette?

Befund
Bizepssehne: Regelrechte Lage der langen Bizepssehne im Sulcus bizipitalis. Unauffällige Darstellung des Bizepssehnenankers.
M. subscapularis: Unauffällig.
M. infraspinatus: Unauffällig.
M. supraspinatus: In den wassersensitiven Sequenzen zeigen sich Signalanhebungen entlang und innerhalb der Supraspinatussehne.
Glenoid: Kleine Konturunterbrechung im anterosuperioren Glenoid, die mit dem sublabralen Foramen vereinbar ist.
Knochen: AC-Gelenksarthrose mit Kapselschwellung und kleiner subakromialer Knochenkonsole mit konsekutivem Impingement der Supraspinatussehne.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Der Befund ist mit einer Tendinitis der Sehne des M. supraspinatus vereinbar. Impingement bei AC-Gelenksarthrose und kleiner subakromialer Knochenkonsole.

* Rö Thx :: 8rthx
Rechtfertigende Indikation
Infiltrat? Stauung?

Befund
Herz: Nicht vergrößert. Keine Zeichen einer akuten kardialen Dekompensation.
Mediastinum:
  Paratracheale Linie: Unauffällig
  Azygoösophageale Linie: Unauffällig
  Paraspinale Linie: Unauffällig
  Paraaortische Linie: Unauffällig
Hili: Unauffällig
Lunge: Ein umschriebenes flächiges Infiltrat lässt sich nicht abgrenzen.
Pleura: Kein Pneumothorax. Scharf abgrenzbares Zwerchfell. Randwinkel frei. Kein Pleuraerguss.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Kein richtungsweisender Befund.

* CT Thorax :: 8cthx
Rechtfertigende Indikation

Technik
Spiral-CT des Thorax unter intravenöser Kontrastmittelgabe.

Befund
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguss.
Nebennieren: Soweit erfasst unauffällig.
Sonstige Oberbauchorgane: Soweit erfasst und beurteilbar unauffällig.
Lungenparenchym: Einzelne unspezifische pulmonale Verdichtungen. Kein Pleuraerguss. Kein Crazy paving. Kein Honeycombing. Keine Konsolidierung. Keine suspekten Rundherde.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Einzelne unspezifische pulmonale Verdichtungen. Kein richtungsweisender Befund.

Einzelne kleine unspezifische ovaläre Verdichtungen. Verlaufskontrolle in 3 Monaten mittels Niedrigdosis-CT angeraten.

* CT Thorax-Abdomen :: 8cthxabd
Rechtfertigende Indikation

Technik
Orale und intravenöse Kontrastmittelgabe. Spiral-CT des Thorax und des gesamten Abdomens in der portalvenösen Phase.

Befund
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguss.
Lungenparenchym: Einzelne unspezifisch pulmonale Verdichtungen. Kein Pleuraerguss. Kein Crazy paving. Kein Honeycombing. Keine Konsolidierung. Keine suspekten Rundherde.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein Nachweis erweiterter intra- oder extrahepatischer Gallenwege. Keine Mehrschichtigkeit der Gallenblase.
Bauchspeicheldrüse: Unauffällig.
Pfortader: Unauffällig.
Aorta: Gefäßsklerose.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflussstörung.
Abdominale Lymphknoten: Einzelne nicht suspekt vergrößerte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Appendix: Durchmesser xx mm (Normwert < 7mm)
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR Mammografie :: 8mmammo

Fragestellung: Malignom?

Sequenzen:

Befund
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Rechte Mamma:
KM aufnehmende Herde:
- Nein/Fokus/Masse/nicht-massig
- Nicht weiter klassifizierbarer Fokus (<5mm)
- KM-aufnehmende Masse
  - Form der Masse: rund/oval/lobuliert/irregulär (suspekt)
  - Rand der Masse: glatt/irregulär/spikuliert
  - T1-reiche Signale innerhalb der Masse: ja (Gutartig: Lymphknoten, Fettnekrose, Hamartom - Verlaufskontrolle nötig zum Ausschluss eines Wachstums)/nein
  - T2FS-reiche Signale innerhalb der Masse: ja/nein (suspekt).
  - KM-Aufnahme: homogen/randständig (40%-ige Malignomwahrscheinlichkeit)/septiert
  - Septierungen: nein/ja und KM-aufnehmend (suspekt)/ja aber nicht KM-aufnehmend (Fibroadenom)
  - Nidus: ja (suspekt)/nein
  - KM Kinetik: Typ I (6%), Typ II (6 - 77%), Typ III (29-77%)
- Nicht-massige KM-Aufnahme
  - Form: linear, nicht ductal (31%)/ductal (60%)/segmental, multiductal (78%)/regional(21%)/gruppiert(60%)
Brustdrüsenkörper: unauffällig
Cutis: unauffällig
Mamille: unauffällig
Brustwand: unauffällig
Axilläre Lymphknoten: unauffällig

Linke Mamma:
KM aufnehmende Herde:
- Nein/Fokus/Masse/nicht-massig
- Nicht weiter klassifizierbarer Fokus (<5mm)
- KM-aufnehmende Masse
  - Form der Masse: rund/oval/lobuliert/irregulär (suspekt)
  - Rand der Masse: glatt/irregulär/spikuliert
  - T1-reiche Signale innerhalb der Masse: ja (Gutartig: Lymphknoten, Fettnekrose, Hamartom - Verlaufskontrolle nötig zum Ausschluss eines Wachstums)/nein
  - T2FS-reiche Signale innerhalb der Masse: ja/nein (suspekt).
  - KM-Aufnahme: homogen/randständig (40%-ige Malignomwahrscheinlichkeit)/septiert
  - Septierungen: nein/ja und KM-aufnehmend (suspekt)/ja aber nicht KM-aufnehmend (Fibroadenom)
  - Nidus: ja (suspekt)/nein
  - KM Kinetik: Typ I (6%), Typ II (6 - 77%), Typ III (29-77%)
- Nicht-massige KM-Aufnahme
  - Form: linear, nicht ductal (31%)/ductal (60%)/segmental, multiductal (78%)/regional(21%)/gruppiert(60%)
Brustdrüsenkörper: unauffällig
Cutis: unauffällig
Mamille: unauffällig
Brustwand: unauffällig
Axilläre Lymphknoten: unauffällig
Beurteilung


Rechts Bi-RADS:
Links Bi-RADS:: 

0 - weitere Diagnostik nötig
1 - unauffällig
2 - kein Malignom
3 - Verlaufskontrolle nötig
4 - Biopsie nötig
5 - Mamma-Karzinom sehr wahrscheinlich
6 - Bekanntes Karzinom

Prozentangaben in Klammern stehen jeweils für die Malignomwahrscheinlichkeit.
Basiert auf: http://radiologyassistant.nl/en/p47a585a7401a9/breast-mri.html
* MR Ellenbogen :: 8mell

Klinische Angaben:

Befund
Distale Bizepssehne: Unauffällig
Kollateralbänder: Unauffällig
Knochen: Unauffällig
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.
Beurteilung

* CT Abdomen :: 8cabd
Rechtfertigende Indikation

Technik
Orale und intravenöse Kontrastmittelgabe. Spiral-CT des Oberbauches in der arteriellen Phase. Spiral-CT des gesamten Abdomens in der portalvenösen Phase.

Befund
Basale Lungenabschnitte: Unauffällig. Kein Pleuraerguss. Kein Perikarderguss. Keine freie Luft.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein Nachweis erweiterter intra- oder extrahepatischer Gallenwege. Keine Mehrschichtigkeit der Gallenblase.
Bauchspeicheldrüse: Unauffällig.
Arterien: Gefäßsklerose.
Pfortader: Unauffällig.
Lebervenen: Unauffällig.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflussstörung.
Lymphknoten: Einzelne nicht suspekt vergrößerte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR LWS :: 8mlws
Fragestellung
Lumbale Beschwerden. Degeneration?

Befund
Numerierung: Der Wirbelkörper mit Anheftung des Lig. iliolumbale wird im Folgenden als LWK5 betrachtet.
Hinterkante: Harmonischer Verlauf.
Höhenminderung von Wirbelkörpern: Nein.
Myelon: Unauffällige Darstellung des Conus medullaris und der Cauda equina.
Facettengelenke: Multisegmentale Facettenhypertrophie.
ISG: Mäßig degenerativ verändert.
LWK1/2: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK2/3: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK3/4: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK4/5: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK5/SWK1: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR ISG :: 8misg
Fragestellung:
Sakroileitis?

Technik:
MRT der ISG nach SOP nativ.

Befund:
Paraartikuläre Osteitis: Nein
Kapsulitis: Nein
Enthesitis: Kein Anhalt
Erosionen: Nein
Fettmetaplasie des paraartikulären Knochenmarkes: Nein
Transartikuläre Knochenbrücken: Nein
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung:
Keine "aktive Sakroiliites" nach den ASAG-Kriterien.
Kein Anhalt für eine Osteitis condens oder eine Arthrosis deformans.

* Knochendichte :: 8mkd
Technik
CT Dickschichtmessung von mehreren nicht frakturierten unteren Wirbelkörpern unter gleichzeitiger Messung eines Referenzkörpers. Computerassistierte Auswertung der Knochendichte.

Befund
Die Knochendichte beträgt im Mittel:

Im Vergleich zum altersangepassten Kollektiv weicht dieser Wert um XXX Standardabweichungen ab (Z-Wert).

Im Vergleich zum Normalkollektiv (20 jährige Erwachsene) weicht dieser Wert um XXX Standartabweichungen ab (T-Wert).

Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Altersentsprechende Osteopenie.

* PRT :: 8mprt
Technik
Planung der Injektion mittels CT. Einbringung einer atraumatischen Chibanadel bis vor die Nervenwurzel. Lagekontrolle nach Gabe von Kontrastmittel. Applikation von Triamcinolon und 2 ml Bupivacain.

Beurteilung
Komplikationslose CT-gesteuerte periradikuläre Therapie der Nervenwurzel
* Knie :: 8mknie
Klinische Angaben

Befund
Außenmeniskus: Keine eindeutige Konturunterbrechung. Kein Amputationszeichen in der koronaren Ansicht. Kein Anhalt für eine Ruptur der meniskokapsulären Anheftung.
Innenmeniskus: Keine eindeutige Konturunterbrechung. Kein Amputationszeichen in der koronaren Ansicht. Kein Anhalt für eine Ruptur der meniskokapsulären Anheftung.
Hinteres Kreuzband: Unauffällig.
Vorderes Kreuzband: Unauffällig.
Kollateralbänder:  Unauffällig.
Retropatellarer chondraler Gelenküberzug: Unauffällig.
Femorotibialer  chondraler Gelenküberzug: Unauffällig.
Erguss: Kein signifikanter Erguss.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR OSG :: 8mosg
Klinische Angaben: Distorsion

Befund
Knochen: unauffällig
Syndesmose: unauffällig
Außenbänder: unauffällig
Innenband: unauffällig
Peronealsehnen: unauffällig
Mediale Beugesehnen: 
Achillessehne: unauffällig
Strecksehnen: unauffällig
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* kleines
- 8zv :: Zum Vergleich liegt eine Voruntersuchung vom XXX vor.
- 8bp :: Breitbasige dorsale Protrusion.
- 8be :: Breitbasige dorsale Extrusion.
- 8glsa :: Geringe lineare Signalanhebungen, die die Oberfläche nicht eindeutig überschreiten.
- 8rm :: Rotatorenmanschette
- 8nph1 :: Deutlich erweitert. Spitzwinkeliges posteriores Corpus callosum.
- 8nph2 :: Prominente innere Liquorräume und spitzwinkeliges posteriores Corpus callosum. Bei entsprechender Klinik ist der Befund mit einem Normaldruckhydrozephalus (NPH) vereinbar.
- 8covid ::
Checkliste COVID-19
Milchglastrübung oder Konsolidierung vorhanden:
Runde Morpholgie der Transparenzminderungen:
Mehr als zwei Lungenlappen beteiligt:
Beide Lungen beteiligt: 
Keine axiale Lungenbeteiligung:
Periphere Lungenbeteiligung:
Crazy paving pattern:
Reverser Halo:
- 8perf ::

CT-Perfusion:
Die Beurteilung erfolgt anhand des visuellen Eindruckes, da im DICOM-Datensatz keine plausiblen Messwerte enthalten sind.
Seitendifferenz TTP > 4s: ja/nein
Areale mit einer MTT > 6s: ja/nein
Areale mit einer CBF < 15 ml/100g/min: nein
Areale mit einer CBV > 6 ml/100g: nein
Areale mit einer CBV < 2 ml/100g: nein/CBV-ASPECT-Score: 10 (experimentell)
TTD/CBV-Mismatch: ja/nein/nicht beurteilbar, bei ACI Verschluss
