Befunde sollten verständlich sein. Verständlichkeit erreicht man über vier Mittel: Einfachheit, Prägnanz, Struktur und Leseanreize. In diesem Sinne möchte ich gerne radiologische Befunde optimieren.

* CC-Lizenz zur freien Verwendung

Die Texte sind zur freien Verwendung mit der [[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International License]] Lizenz versehen.

* CCT
Befund
Innere Liquorräume: unauffälig
Äußere Liquorräume: unauffällig
Mittellinie: nicht verlagert
Mark-Rinden-Differenzierung: allseits erhalten
Basalganglien: seitengleich abgrenzbar.
Nasennebenhölhlen : Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.
Blutungssuspekte Dichteanhebungen: nein

Beurteilung
Keine Zeichen eines erhöhten Hirndruckes. Kein Anhalt für eine intrakranielle Einblutung. Ein frischer territorialer Infarkt demakiert sich nicht.

* cMRT
Befund:
Normale Weite der inneren und äußeren Liquorräume. Keine Verlagerung der Mittellinie. Allseits erhaltene Mark-Rinden-Differenzierung. Unauffällige Darstellung der Basalganglien, des Hirnstammes und des Kleinhirnes. Unauffällige Signale der Nasennebenhöhlen und der Mastoidzellen soweit erfasst. Keine Diffusionsstörung. Keine pathologischen Signalanhebungen in der T1w. Einzelne unspezifische Signalanhebungen im Bereich des periventrikulären Marklagers in der T2 und FLAIR.

Beurteilung:
Einzelne unspezfische Marklagerveränderungen u.a. vereinbar mit mikroangiopathisch bedingten Veränderungen. Ansonsten kein richtungsweisender Befund.

* CT-NNH
Rechtfertigende Indikation: Belüftung der Nasennebenhöhlen?

Beurteilung:
Sinus frontales: Unauffällige Belüftung.
Sinus ethmoidales: Unauffällige Belüftung.
Sinus sphenoidales: Unauffällige Belüftung.
Sinus maxillares: Unauffällige Belüftung.
Mastoidzellen: Unauffällige Belüftung.

* HWS
Harmonischer Verlauf der Hinterkante. Keine Höhenminderung der abgebildeten Wirbelkörper. Orientierend unauffällige Darstellung der miterfassten basalen Hirnabschnitte. Unauffällige Darstellung des Myelons.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.

* Schulter
Bizepssehne: Regelrechte Lage der langen Bizepssehne im Sulcus bizipitalis. Unauffällige Darstellung des Bizepssehnenankers.
M. subscapularis: Unauffällige Darstellung.
M. infraspinatus: Unauffällige Darstellung.
M. supraspinatus: In den wassersensitiven Sequenzen zeigen sich Signalanhebungen entlang und innerhalb der Supraspinatussehne.
Glenoid: Kleine Konturunterbrechung im ventralen Glenoid, die mit dem sublabralen Foramen vereinbar ist.
Knochen: AC-Gelenksarthrose mit Kapselschwellung und kleiner subakromialer Knochenkonsole mit konsekutivem Impingement der Supraspinatussehne.

Beurteilung: Der Befund ist mit einer Tendinitis der Sehne des M. supraspinatus vereinbar. Impingement bei AC-Gelenksarthrose und kleiner subakromialer Knochenkonsole.

* Rö Thx
Paratracheale Linie: unauffällig
Azygoösophageale Linie: unauffällig
Paraspinale Linie: unauffällig
Paraaortische Linie: unauffällig
Zwerchfell: scharf abgrenzbar
Randwinkel: frei. 
Pleura: Kein Pneumothorax. Kein Pleuraerguß.
Herz: Nicht vergrößert. Keine Zeichen einer akuten kardialen Dekompensation.
Lunge: Ein umschriebenes flächiges Infiltrat lässt sich nicht abgrenzen.
Mediastinum: Schlank und mittelständig.

* CT Thorax
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguß.
Lungenparenchym: Einzelne unspezifisch pulmonale Verdichtungen. Kein Pleuraerguß.

* CT Abdomen
Basale Lungenabschnitte: Unauffällig. Kein Pleuraerguß. Kein Pericarderguß.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein  Nachweis erweiterter intra- oder extrahepatischer Gallenwege.
Bauchspeicheldrüse: Unauffällig.
Pfortader: Unauffällig.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflusstörung.
Lymphknoten: Einzelne nicht suspekte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.

* LWS
Harmonischer Verlauf der Hinterkante. Keine Höhenminderung der abgebildeten Wirbelkörper. Unauffällige Darstellung des Conus medullaris und der Cauda equina. Multisegmentale Facettenhypertrophie.
LWK1/2: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK2/3: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK3/4: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK4/5: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK5/SWK1: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.

* Knie
Außenmeniskus: unauffällig
Innenmeniskus: unauffällig
Hinteres Kreuzband: unauffällig
Vorderes Kreuzband: unauffällig
Kollateralbänder:  unauffällig
Retropatellarer chondraler Gelenküberzug: unauffällig
Femorotibialer  chondraler Gelenküberzug: unauffällig
Kein signifikanter Erguß.

* Osteo
Technik: CT Dickschichtmessung von mehreren nicht frakturierten unteren Wirbelkörpern unter gleichzeitiger Messung eines Referenzkörpers. Computerassistierte Auswertung der Knochendichte.

Befund:

Die Knochendichte beträgt im Mittel:

Im Vergleich zum altersangepassten Kollektiv weicht dieser Wert um XXX Standardabweichungen ab (Z-Wert).

Im Vergleich zum Normalkollektiv (20 jährige Erwachsene) weicht dieser Wert um XXX Standartabweichungen ab (T-Wert).

Beurteilung:
Altersentsprechende Osteopenie.

