Befunde sollten verständlich sein. Verständlichkeit erreicht man über vier Mittel: Einfachheit, Prägnanz, Struktur und Leseanreize. In diesem Sinne möchte ich gerne radiologische Befunde optimieren.

* CC-Lizenz zur freien Verwendung

Die Texte sind zur freien Verwendung mit der [[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International License]] Lizenz versehen.

* CCT
Rechtfertigende Indikation
Blutung? Ischämie? Hirndruck?

Technik
Sequentielles natives CCT.

Befund
Blutungssuspekte Dichteanhebungen: Nein.
Innere Liquorräume: Unauffällig.
Äußere Liquorräume: Unauffällig.
Mittellinie: Nicht verlagert.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Venöse Sinus: Soweit beurteilbar unauffällig.
Nasennebenhöhlen: Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.


Beurteilung
Keine Zeichen eines erhöhten Hirndruckes. Kein Anhalt für eine intrakranielle Einblutung. Ein frischer territorialer Infarkt demarkiert sich nicht.

* cMRT
Klinische Angaben

Befund
Diffusionsstörung: Nein.
Pathologische Signalanhebungen in der T1w: Nein.
Innere Liquorräume: Unauffällig.
Äußere Liquorräume: Unauffällig.
Mittellinie: Nicht verlagert.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Hirnstamm: Unauffällig.
Kleinhirn: Unauffällig.
Marklager: Einzelne unspezifische Signalanhebungen im Bereich des periventrikulären Marklagers in der T2 und FLAIR.
Nasennebenhölhlen: Unauffällige Signale soweit erfasst.
Mastoidzellen: Unauffällige Signale soweit erfasst.

Beurteilung
Einzelne unspezfische Marklagerveränderungen. Diese sind unter anderem mit mikroangiopathisch bedingten Veränderungen vereinbar. Ansonsten kein richtungsweisender Befund.

* CT-NNH
Rechtfertigende Indikation
Belüftung der Nasennebenhöhlen?

Technik
Spiral-CT der Nasennebenhöhlen

Beurteilung
Sinus frontales: Unauffällige Belüftung.
Sinus ethmoidales: Unauffällige Belüftung.
Sinus sphenoidales: Unauffällige Belüftung.
Sinus maxillares: Unauffällige Belüftung.
Mastoidzellen: Unauffällige Belüftung.
Spiegelbildungen: Nein.

* HWS
Rechtfertigende Indikation
Spinale Enge? Degeneration?

Technik
Spiral-CT der HWS.

Hinterkante: Harmonischer Verlauf.
Höhenminderungen von Wirbelkörpern: Nein.
Miterfasste basale Hirnabschnitte: Unauffällig soweit erfasst.
HWK1/2: Keine Fraktur. Atlantodentalarthrose.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.

Beurteilung

* Schulter
Fragestellung

Bizepssehne: Regelrechte Lage der langen Bizepssehne im Sulcus bizipitalis. Unauffällige Darstellung des Bizepssehnenankers.
M. subscapularis: Unauffällige Darstellung.
M. infraspinatus: Unauffällige Darstellung.
M. supraspinatus: In den wassersensitiven Sequenzen zeigen sich Signalanhebungen entlang und innerhalb der Supraspinatussehne.
Glenoid: Kleine Konturunterbrechung im anterosuperioren Glenoid, die mit dem sublabralen Foramen vereinbar ist.
Knochen: AC-Gelenksarthrose mit Kapselschwellung und kleiner subakromialer Knochenkonsole mit konsekutivem Impingement der Supraspinatussehne.

Beurteilung
Der Befund ist mit einer Tendinitis der Sehne des M. supraspinatus vereinbar. Impingement bei AC-Gelenksarthrose und kleiner subakromialer Knochenkonsole.

* Rö Thx
Rechtfertigende Indikation

Befund
Paratracheale Linie: Unauffällig.
Azygoösophageale Linie: Unauffällig.
Paraspinale Linie: Unauffällig.
Paraaortische Linie: Unauffällig.
Zwerchfell: Scharf abgrenzbar.
Randwinkel: Frei.
Pleura: Kein Pneumothorax. Kein Pleuraerguss.
Herz: Nicht vergrößert. Keine Zeichen einer akuten kardialen Dekompensation.
Lunge: Ein umschriebenes flächiges Infiltrat lässt sich nicht abgrenzen.
Mediastinum: Schlank und mittelständig.

* CT Thorax
Rechtfertigende Indikation

Technik
Spiral-CT des Thorax unter intravenöser Kontrastmittelgabe.

Befund
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguss.
Nebennieren: Soweit erfasst unauffällig.
Sonstige Oberbauchorgane: Soweit erfasst und beurteilbar unauffällig.
Lungenparenchym: Einzelne unspezifisch pulmonale Verdichtungen. Kein Pleuraerguss. Kein Crazy paving. Kein Honeycombing. Keine Konsolidierung. Keine suspekten Rundherde.
Skelettsystem: Degenerative Veränderungen.

Beurteilung
Einzelne unspezifische pulmonale Verdichtungen. Kein richtungsweisender Befund.

Einzelne kleine unspezifische ovaläre Verdichtungen. Verlaufskontrolle in 3 Monaten mittels Niedrigdosis-CT angeraten.

* CT Abdomen
Rechtfertigende Indikation

Technik
Orale und intravenöse Kontrastmittelgabe. Spiral-CT des Oberbauches in der arteriellen Phase. Spiral-CT des gesamten Abdomens in der portalvenösen Phase.

Befund
Basale Lungenabschnitte: Unauffällig. Kein Pleuraerguss. Kein Perikarderguss.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein Nachweis erweiterter intra- oder extrahepatischer Gallenwege. Keine Mehrschichtigkeit der Gallenblase.
Bauchspeicheldrüse: Unauffällig.
Pfortader: Unauffällig.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflussstörung.
Lymphknoten: Einzelne nicht suspekt vergrößerte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.
Skelettsystem: Degenerative Veränderungen.

Beurteilung

* LWS
Rechtfertigende Indikation
Lumbale Beschwerden. Degeneration?

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderung von Wirbelkörpern: Nein.
Myelon: Unauffällige Darstellung des Conus medullaris und der Cauda equina.
Facettengelenke: Multisegmentale Facettenhypertrophie.
LWK1/2: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK2/3: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK3/4: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK4/5: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK5/SWK1: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.

Beurteilung

* Knie
Klinische Angaben

Befund
Außenmeniskus: unauffällig.
Innenmeniskus: unauffällig.
Hinteres Kreuzband: unauffällig.
Vorderes Kreuzband: unauffällig.
Kollateralbänder:  unauffällig.
Retropatellarer chondraler Gelenküberzug: unauffällig.
Femorotibialer  chondraler Gelenküberzug: unauffällig.
Erguss: Kein signifikanter Erguss.

Beurteilung

* Knochendichte
Technik
CT Dickschichtmessung von mehreren nicht frakturierten unteren Wirbelkörpern unter gleichzeitiger Messung eines Referenzkörpers. Computerassistierte Auswertung der Knochendichte.

Befund
Die Knochendichte beträgt im Mittel:

Im Vergleich zum altersangepassten Kollektiv weicht dieser Wert um XXX Standardabweichungen ab (Z-Wert).

Im Vergleich zum Normalkollektiv (20 jährige Erwachsene) weicht dieser Wert um XXX Standartabweichungen ab (T-Wert).

Beurteilung
Altersentsprechende Osteopenie.

