Befunde sollten verständlich sein. Verständlichkeit erreicht man über vier Mittel: Einfachheit, Prägnanz, Struktur und Leseanreize. In diesem Sinne möchte ich gerne radiologische Befunde optimieren.

* CC-Lizenz zur freien Verwendung

Die Texte sind zur freien Verwendung mit der [[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International License]] Lizenz versehen.

* CCT :: 8cct
Rechtfertigende Indikation
Blutung? Ischämie? Hirndruck?

Technik
Sequentielles natives CCT.

Befund
Blutungssuspekte Dichteanhebungen: Nein.
Innere Liquorräume: Mäßig erweitert. Keine NPH-Konfiguration.
Äußere Liquorräume: Mäßig erweitert. Keine temporomesial betonte Atrophie.
Mittellinie: Nicht verlagert.
Mediazeichen: Nein.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Venöse Sinus: Soweit beurteilbar unauffällig.
Nasennebenhöhlen: Unauffällige Belüftung soweit erfasst.
Mastoidzellen: Unauffällige Belüftung soweit erfasst.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Keine Zeichen eines erhöhten Hirndruckes. Kein Anhalt für eine intrakranielle Einblutung. Ein frischer territorialer Infarkt demarkiert sich nicht.

* MRT Gehirn :: 8cmr
Klinische Angaben

Befund
Diffusionsstörung: Nein.
Pathologische Signalanhebungen in der T1w: Nein.
Innere Liquorräume: Unauffällig. Keine NPH-Konfiguration.
Äußere Liquorräume: Unauffällig. Keine signifikante temporomesiale Atrophie.
Mittellinie: Nicht verlagert.
Mark-Rinden-Differenzierung: Allseits erhalten.
Basalganglien: Seitengleich abgrenzbar.
Hirnstamm: Unauffällig.
Kleinhirn: Unauffällig. Auch unauffällige Lage der Kleinhirntonsillen.
Marklager: In der T2w und in der FLAIR zeigen sich einzelne unspezifische Signalanhebungen im periventrikulären Marklager.
Nasennebenhöhlen: Soweit erfasst unauffällige Signale.
Mastoidzellen: Soweit erfasst unauffällige Signale. Frei einsehbarer innerer Gehörgang.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Einzelne unspezifsche Marklagerveränderungen. Diese sind gut mit mikroangiopathisch und lakunär bedingten Veränderungen vereinbar. Ansonsten kein richtungsweisender Befund.

* CT-NNH :: 8cnnh
Rechtfertigende Indikation
Belüftung der Nasennebenhöhlen?

Technik
Spiral-CT der Nasennebenhöhlen

Beurteilung
Sinus frontales: Unauffällige Belüftung.
Sinus ethmoidales: Unauffällige Belüftung.
Sinus sphenoidales: Unauffällige Belüftung.
Sinus maxillares: Unauffällige Belüftung.
Mastoidzellen: Unauffällige Belüftung.
Spiegelbildungen: Nein.
Nasenseptum: Leichte Deviation.
Conchae nasalis: Unauffällig.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

* CT-Felsenbein :: 8cfb
Rechtfertigende Indikation
Pathologie der Felsenbeine?

Technik
Spiral-CT der Felsenbeine

Befund
Mastoidzellen: Unauffällige Belüftung.
Bogengänge: Unauffällig.
Gehörknöchelchen: Unauffällig.
Äußerer Gehörgang: Unauffällig.
Prussak-Raum: Unauffällig.
Scutum: Unauffällig.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung:
Kein richtungsweisender Befund

* CT-HWS :: 8chws
Rechtfertigende Indikation
Spinale Enge? Degeneration?

Technik
Spiral-CT der HWS.

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderungen von Wirbelkörpern: Nein.
Miterfasste basale Hirnabschnitte: Unauffällig soweit erfasst.
HWK1/2: Keine Fraktur.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR-HWS :: 8mhws
Fragestellung
Spinale Enge? Degeneration?

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderungen von Wirbelkörpern: Nein.
Miterfasste basale Hirnabschnitte: Unauffällig soweit erfasst.
HWK1/2: Keine Fraktur.
HWK2/3: Kein Nachweis einer signifikanten spinalen Einengung.
HWK3/4: Kein Nachweis einer signifikanten spinalen Einengung.
HWK4/5: Kein Nachweis einer signifikanten spinalen Einengung.
HWK5/6: Kein Nachweis einer signifikanten spinalen Einengung.
HWK6/7: Kein Nachweis einer signifikanten spinalen Einengung.
HWK7/BWK1: Kein Nachweis einer signifikanten spinalen Einengung.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MRT Schulter :: 8mschul
Klinische Angaben

Befund
Bizepssehne: Regelrechte Lage der langen Bizepssehne im Sulcus bizipitalis. Unauffällige Darstellung des Bizepssehnenankers.
M. subscapularis: Unauffällig.
M. infraspinatus: Unauffällig.
M. supraspinatus: In den wassersensitiven Sequenzen zeigen sich Signalanhebungen entlang und innerhalb der Supraspinatussehne.
Glenoid: Kleine Konturunterbrechung im anterosuperioren Glenoid, die mit dem sublabralen Foramen vereinbar ist.
Knochen: AC-Gelenksarthrose mit Kapselschwellung und kleiner subakromialer Knochenkonsole mit konsekutivem Impingement der Supraspinatussehne.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Der Befund ist mit einer Tendinitis der Sehne des M. supraspinatus vereinbar. Impingement bei AC-Gelenksarthrose und kleiner subakromialer Knochenkonsole.

* Rö Thx :: 8rthx
Rechtfertigende Indikation
Infiltrat? Stauung?

Befund
Herz: Nicht vergrößert. Keine Zeichen einer akuten kardialen Dekompensation.
Mediastinum:
  Paratracheale Linie: Unauffällig
  Azygoösophageale Linie: Unauffällig
  Paraspinale Linie: Unauffällig
  Paraaortische Linie: Unauffällig
Hili: Unauffällig
Lunge: Ein umschriebenes flächiges Infiltrat lässt sich nicht abgrenzen.
Pleura: Kein Pneumothorax. Scharf abgrenzbares Zwerchfell. Randwinkel frei. Kein Pleuraerguss.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Kein richtungsweisender Befund.

* CT Thorax :: 8cthx
Rechtfertigende Indikation

Technik
Spiral-CT des Thorax unter intravenöser Kontrastmittelgabe.

Befund
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguss.
Nebennieren: Soweit erfasst unauffällig.
Sonstige Oberbauchorgane: Soweit erfasst und beurteilbar unauffällig.
Lungenparenchym: Einzelne unspezifisch pulmonale Verdichtungen. Kein Pleuraerguss. Kein Crazy paving. Kein Honeycombing. Keine Konsolidierung. Keine suspekten Rundherde.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Einzelne unspezifische pulmonale Verdichtungen. Kein richtungsweisender Befund.

Einzelne kleine unspezifische ovaläre Verdichtungen. Verlaufskontrolle in 3 Monaten mittels Niedrigdosis-CT angeraten.

* CT Thorax-Abdomen
Rechtfertigende Indikation

Technik
Orale und intravenöse Kontrastmittelgabe. Spiral-CT des Thorax und des gesamten Abdomens in der portalvenösen Phase.

Befund
Axilla: Einzelne nicht suspekte Lymphknoten.
Mediastinum: Einzelne nicht suspekte Lymphknoten. Kein Perikarderguss.
Lungenparenchym: Einzelne unspezifisch pulmonale Verdichtungen. Kein Pleuraerguss. Kein Crazy paving. Kein Honeycombing. Keine Konsolidierung. Keine suspekten Rundherde.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein Nachweis erweiterter intra- oder extrahepatischer Gallenwege. Keine Mehrschichtigkeit der Gallenblase.
Bauchspeicheldrüse: Unauffällig.
Pfortader: Unauffällig.
Aorta: Gefäßsklerose.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflussstörung.
Abdominale Lymphknoten: Einzelne nicht suspekt vergrößerte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Appendix: Durchmesser xx mm (Normwert < 7mm)
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR Mammografie

Fragestellung: Malignom?

Sequenzen:

Befund
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Rechte Mamma:
KM aufnehmende Herde:
- Nein/Fokus/Masse/nicht-massig
- Nicht weiter klassifizierbarer Fokus (<5mm)
- KM-aufnehmende Masse
  - Form der Masse: rund/oval/lobuliert/irregulär (suspekt)
  - Rand der Masse: glatt/irregulär/spikuliert
  - T1-reiche Signale innerhalb der Masse: ja (Gutartig: Lymphknoten, Fettnekrose, Hamartom - Verlaufskontrolle nötig zum Ausschluss eines Wachstums)/nein
  - T2FS-reiche Signale innerhalb der Masse: ja/nein (suspekt).
  - KM-Aufnahme: homogen/randständig (40%-ige Malignomwahrscheinlichkeit)/septiert
  - Septierungen: nein/ja und KM-aufnehmend (suspekt)/ja aber nicht KM-aufnehmend (Fibroadenom)
  - Nidus: ja (suspekt)/nein
  - KM Kinetik: Typ I (6%), Typ II (6 - 77%), Typ III (29-77%)
- Nicht-massige KM-Aufnahme
  - Form: linear, nicht ductal (31%)/ductal (60%)/segmental, multiductal (78%)/regional(21%)/gruppiert(60%)
Brustdrüsenkörper: unauffällig
Cutis: unauffällig
Mamille: unauffällig
Brustwand: unauffällig
Axilläre Lymphknoten: unauffällig

Linke Mamma:
KM aufnehmende Herde:
- Nein/Fokus/Masse/nicht-massig
- Nicht weiter klassifizierbarer Fokus (<5mm)
- KM-aufnehmende Masse
  - Form der Masse: rund/oval/lobuliert/irregulär (suspekt)
  - Rand der Masse: glatt/irregulär/spikuliert
  - T1-reiche Signale innerhalb der Masse: ja (Gutartig: Lymphknoten, Fettnekrose, Hamartom - Verlaufskontrolle nötig zum Ausschluss eines Wachstums)/nein
  - T2FS-reiche Signale innerhalb der Masse: ja/nein (suspekt).
  - KM-Aufnahme: homogen/randständig (40%-ige Malignomwahrscheinlichkeit)/septiert
  - Septierungen: nein/ja und KM-aufnehmend (suspekt)/ja aber nicht KM-aufnehmend (Fibroadenom)
  - Nidus: ja (suspekt)/nein
  - KM Kinetik: Typ I (6%), Typ II (6 - 77%), Typ III (29-77%)
- Nicht-massige KM-Aufnahme
  - Form: linear, nicht ductal (31%)/ductal (60%)/segmental, multiductal (78%)/regional(21%)/gruppiert(60%)
Brustdrüsenkörper: unauffällig
Cutis: unauffällig
Mamille: unauffällig
Brustwand: unauffällig
Axilläre Lymphknoten: unauffällig
Beurteilung


Rechts Bi-RADS:
Links Bi-RADS:: 

0 - weitere Diagnostik nötig
1 - unauffällig
2 - kein Malignom
3 - Verlaufskontrolle nötig
4 - Biopsie nötig
5 - Mamma-Karzinom sehr wahrscheinlich
6 - Bekanntes Karzinom

Prozentangaben in Klammern stehen jeweils für die Malignomwahrscheinlichkeit.
Basiert auf: http://radiologyassistant.nl/en/p47a585a7401a9/breast-mri.html
* MR Ellenbogen

Klinische Angaben:

Befund
Distale Bizepssehne: Unauffällig
Kollateralbänder: Unauffällig
Knochen: Unauffällig
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.
Beurteilung

* CT Abdomen
Rechtfertigende Indikation

Technik
Orale und intravenöse Kontrastmittelgabe. Spiral-CT des Oberbauches in der arteriellen Phase. Spiral-CT des gesamten Abdomens in der portalvenösen Phase.

Befund
Basale Lungenabschnitte: Unauffällig. Kein Pleuraerguss. Kein Perikarderguss. Keine freie Luft.
Leber: Homogenes Leberparenchym.
Gallenwege: Kein Nachweis röntgendichter Konkremente. Kein Nachweis erweiterter intra- oder extrahepatischer Gallenwege. Keine Mehrschichtigkeit der Gallenblase.
Bauchspeicheldrüse: Unauffällig.
Pfortader: Unauffällig.
Aorta: Gefäßsklerose.
Milz: Unauffällig.
Nebennieren: Unauffällig.
Nieren: Beidseits normal groß. Keine Zeichen einer Harnabflussstörung.
Lymphknoten: Einzelne nicht suspekt vergrößerte mesenteriale, paraaortale und inguinale Lymphknoten.
Darm: Soweit CT morphologisch beurteilbar unauffällig.
Becken: Keine freie Flüssigkeit. Soweit beurteilbar unauffällige Darstellung der erfassten Organe des kleinen Beckens.
Skelettsystem: Degenerative Veränderungen.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* MR LWS :: 8mlws
Fragestellung
Lumbale Beschwerden. Degeneration?

Befund
Hinterkante: Harmonischer Verlauf.
Höhenminderung von Wirbelkörpern: Nein.
Myelon: Unauffällige Darstellung des Conus medullaris und der Cauda equina.
Facettengelenke: Multisegmentale Facettenhypertrophie.
ISG: Mäßig degenerativ verändert.
LWK1/2: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK2/3: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK3/4: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK4/5: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
LWK5/SWK1: Kein Nachweis einer signifikanten neuroforaminalen oder spinalen Stenose.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* Knochendichte
Technik
CT Dickschichtmessung von mehreren nicht frakturierten unteren Wirbelkörpern unter gleichzeitiger Messung eines Referenzkörpers. Computerassistierte Auswertung der Knochendichte.

Befund
Die Knochendichte beträgt im Mittel:

Im Vergleich zum altersangepassten Kollektiv weicht dieser Wert um XXX Standardabweichungen ab (Z-Wert).

Im Vergleich zum Normalkollektiv (20 jährige Erwachsene) weicht dieser Wert um XXX Standartabweichungen ab (T-Wert).

Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung
Altersentsprechende Osteopenie.

* PRT
Technik
Planung der Injektion mittels CT. Einbringung einer atraumatischen Chibanadel bis vor die Nervenwurzel. Lagekontrolle nach Gabe von Kontrastmittel. Applikation von Triamcinolon und 2 ml Bupivacain.

Beurteilung
Komplikationslose CT-gesteuerte periradikuläre Therapie der Nervenwurzel
* Knie
Klinische Angaben

Befund
Außenmeniskus: unauffällig.
Innenmeniskus: unauffällig.
Hinteres Kreuzband: unauffällig.
Vorderes Kreuzband: unauffällig.
Kollateralbänder:  unauffällig.
Retropatellarer chondraler Gelenküberzug: unauffällig.
Femorotibialer  chondraler Gelenküberzug: unauffällig.
Erguss: Kein signifikanter Erguss.
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* OSG
Klinische Angaben: Distorsion

Befund
Knochen: unauffällig
Syndesmose: unauffällig
Außenbänder: unauffällig
Innenband: unauffällig
Peronealsehnen: unauffällig
Achillessehne: unauffällig
Sonstige Sehnen: unauffällig
Voraufnahmen: Liegen zum Befundungszeitpunkt nicht vor.

Beurteilung

* kleines
- 8zv :: Zum Vergleich liegt eine Voruntersuchugn vom XXX vor.
